[tool.poetry]
name = "jpt-nb-corpus"
version = "0.1.0"
description = ""
authors = ["Konstantin Grotov"]
license = "MIT"
packages = [
    { include = "*/*.py" },
]

[tool.poetry.dependencies]
python = "^3.9"
gast = "^0.5.1"
SQLAlchemy = "^1.4.22"
radon = "^5.0.1"
ray = "^1.5.0"
tqdm = "^4.61.2"
spacy = "^3.1.1"
spacy-langdetect = "^0.1.2"
nbformat = "^5.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

