[tool.poetry]
name = "jpt-nb-corpus"
version = "0.1.0"
description = ""
authors = ["konstantgr <60608301+konstantgr@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
