[tool.poetry]
name = "notebook_analyzer"
version = "0.1.0"
description = ""
authors = ["konstantgr <60608301+konstantgr@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "^1.4.22"
gast = "^0.5.2"
radon = "^5.0.1"
nbformat = "^5.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
