#    engine: postgresql
#    host: localhost:0000
#    name: newdb
#    route_to_db: postgresql://@localhost:0000/newdb

sql:
    engine: sqlite
    host: localhost:0000
    name: ../databases/testdb.db

ray_multiprocessing:
    num_cpu: 6

data:
    route_to_notebooks: ../databases/ntbs_list.json
    route_to_scripts: ../databases/20kk_scripts_abs.txt
    download_scripts: False
    download_notebooks: True
    sample_size: 100
    seed: 8

    pbar_using_limit: 1000

metrics:
    'markdown':
      'cell_language': False
      'sentences_count': False
      'unique_words': False
      'content': False

    'code':
      'code_instructions_count': True
      'code_imports': True
      'code_chars_count': True
      'metrics': True

    'notebook':
      'general_metrics': True
      'complexity_metrics': True
      'coupling_between_cells': True
      'coupling_between_functions': True
      'coupling_between_methods': True
      'functions_statistics': True
