db:
  create_database: True

sql:
   engine: sqlite
   pg_name: postgres
   password: postgres
   host: localhost:5432
   name: ../databases/example_db.db

ray_multiprocessing:
    num_cpu: 3

data:
    route_to_notebooks: example_data/example_mapping.json
    route_to_scripts:  example_data/example_mapping.json
    download_scripts: False
    download_notebooks: True
    sample_size: 5
    seed: 12
    progress_bar_limit: 50000

metrics:
    'markdown':
      'cell_language': False
      'sentences_count': False
      'unique_words': False
      'content': False

    'code':
      'code_instructions_count': True
      'code_imports': True
      'code_chars_count': True
      'metrics': True

    'notebook':
      'general_metrics': True
      'complexity_metrics': True
      'coupling_between_cells': True
      'coupling_between_functions': True
      'coupling_between_methods': True
      'functions_statistics': True
